#!/bin/bash

vw -b 18 -q ui --rank 10 --l2 0.001 \
  --learning_rate 0.015 --passes 10 --decay_learning_rate 0.97 --power_t 0 \
  -d /scratch/ml-20m/train.vw -f ratings.reg --cache_file ratings.cache
vw -d /scratch/ml-20m/test.vw -t -i ratings.reg -p ratings.pred



